//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoreApp.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   접수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AcceptTitle {
            get {
                return ResourceManager.GetString("AcceptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   배달 호출과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CallDeliveryTitle {
            get {
                return ResourceManager.GetString("CallDeliveryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주문 취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CancleTitle {
            get {
                return ResourceManager.GetString("CancleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CompleateTitle {
            get {
                return ResourceManager.GetString("CompleateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   배송지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomerAddressTitle {
            get {
                return ResourceManager.GetString("CustomerAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   고객 요청사항과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomerNoticeTitle {
            get {
                return ResourceManager.GetString("CustomerNoticeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   고객 연락처과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CustomerTelTitle {
            get {
                return ResourceManager.GetString("CustomerTelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   배달비과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeliveryCost {
            get {
                return ResourceManager.GetString("DeliveryCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   배달 요청사항과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeliveryNoticeTitle {
            get {
                return ResourceManager.GetString("DeliveryNoticeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   할인 금액과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DiscountCost {
            get {
                return ResourceManager.GetString("DiscountCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   처리 중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InProcessTitle {
            get {
                return ResourceManager.GetString("InProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도움말과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LocalizationTitle {
            get {
                return ResourceManager.GetString("LocalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매장관리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ManageTitle {
            get {
                return ResourceManager.GetString("ManageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주문 수락과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OrderAcceptTitle {
            get {
                return ResourceManager.GetString("OrderAcceptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기본 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OrderBastTitle {
            get {
                return ResourceManager.GetString("OrderBastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주문 내역과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OrderInfoTitle {
            get {
                return ResourceManager.GetString("OrderInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   메뉴과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OrderMenu {
            get {
                return ResourceManager.GetString("OrderMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오더번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OrderNoTitle {
            get {
                return ResourceManager.GetString("OrderNoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주문 거절과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OrderRefuseTitle {
            get {
                return ResourceManager.GetString("OrderRefuseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주문목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OrderTitle {
            get {
                return ResourceManager.GetString("OrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   결제 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaymentInfoTitle {
            get {
                return ResourceManager.GetString("PaymentInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영수증 출력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiptOutputTitle {
            get {
                return ResourceManager.GetString("ReceiptOutputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   접수 대기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiveTitle {
            get {
                return ResourceManager.GetString("ReceiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가게 주소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StoreAddress {
            get {
                return ResourceManager.GetString("StoreAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가게 기본 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StoreBaseInfo {
            get {
                return ResourceManager.GetString("StoreBaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가게 기타 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StoreEtcInfo {
            get {
                return ResourceManager.GetString("StoreEtcInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   휴무일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StoreHolyday {
            get {
                return ResourceManager.GetString("StoreHolyday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가게 메뉴과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StoreMenu {
            get {
                return ResourceManager.GetString("StoreMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가게 명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가게 요청사항과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StoreNoticeTitle {
            get {
                return ResourceManager.GetString("StoreNoticeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사업자 등록번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StoreNumber {
            get {
                return ResourceManager.GetString("StoreNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   영업시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StoreOpenCloseTime {
            get {
                return ResourceManager.GetString("StoreOpenCloseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대표자 명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StoreOwner {
            get {
                return ResourceManager.GetString("StoreOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가게 운영 정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StoreSettingInfo {
            get {
                return ResourceManager.GetString("StoreSettingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가게 연락처과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StoreTel {
            get {
                return ResourceManager.GetString("StoreTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업종/형태과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StoreType {
            get {
                return ResourceManager.GetString("StoreType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   총 주문 금액과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TotalOrderCost {
            get {
                return ResourceManager.GetString("TotalOrderCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   총 결제 금액과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TotalPaymentCost {
            get {
                return ResourceManager.GetString("TotalPaymentCost", resourceCulture);
            }
        }
    }
}
